@echo off
title Launching AuditSphere System & AI Service...
echo ==========================================================
echo   Starting AuditSphere All-in-One Services...
echo ==========================================================

echo [1/2] Launching Python AI Microservice (Port 8000)...
start "AuditSphere Python AI Service (Port 8000)" cmd /k "cd /d %~dp0backend\python-ai && python main.py"

echo [2/2] Launching Frontend Nuxt Application (Port 3000)...
cd /d %~dp0frontend
npm run dev
