package main

import (
	"audit-service/models"
)

// getStrategicPlanSeeds returns 100 realistic Strategic Audit Plan records
// across 10 audit pillars aligned with IIA standards and Indonesian regulations (OJK/BI).
func getStrategicPlanSeeds() []models.StrategicPlan {
	return []models.StrategicPlan{
		// =========================================================================
		// PILAR 1: TATA KELOLA PERUSAHAAN & GCG (GoalID: G-001) - SO-IA01 s/d SO-IA10
		// =========================================================================
		{
			Code:               "SO-IA01",
			GoalID:             "G-001",
			StrategicObjective: "Memastikan kepatuhan terhadap kebijakan dan regulasi perusahaan dan institusi terkait (OJK, BI, Kemenkeu)",
			KPI:                "Tingkat kepatuhan organisasi terhadap kebijakan dan regulasi yang berlaku",
			Unit:               "score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80.0", "2025": "82.0", "2026": "84.0", "2027": "85.0", "2028": "86.0"},
			KPIActuals:         map[string]string{"2024": "81.0", "2025": "83.5", "2026": "84.0", "2027": "", "2028": ""},
			InternalAuditSO:    "Melakukan evaluasi kepatuhan berkala terhadap regulasi eksternal dan SOP internal",
			Actual:             "84.0",
			Target:             "84.0",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA02",
			GoalID:             "G-001",
			StrategicObjective: "Meningkatkan independensi dan objektivitas fungsi Internal Audit",
			KPI:                "Skor penilaian independensi audit oleh Komite Audit",
			Unit:               "Score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "4.2", "2025": "4.4", "2026": "4.6", "2027": "4.8", "2028": "5.0"},
			KPIActuals:         map[string]string{"2024": "4.3", "2025": "4.5", "2026": "4.7", "2027": "", "2028": ""},
			InternalAuditSO:    "Menjamin pelaporan fungsional langsung kepada Dewan Komisaris dan Komite Audit",
			Actual:             "4.7",
			Target:             "4.6",
			Calculation:        "102.17%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA03",
			GoalID:             "G-001",
			StrategicObjective: "Efektivitas penanganan sistem pelaporan pelanggaran (Whistleblowing System / WBS)",
			KPI:                "Persentase tindak lanjut laporan WBS terverifikasi dalam waktu 30 hari",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "90", "Q2": "90", "Q3": "95", "Q4": "95"},
			KPIActuals:         map[string]string{"Q1": "92", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Mempercepat proses telaah awal dan verifikasi fakta laporan WBS masuk",
			Actual:             "92",
			Target:             "90",
			Calculation:        "102.22%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA04",
			GoalID:             "G-001",
			StrategicObjective: "Penguatan koordinasi pengawasan dengan Komite Audit dan Dewan Komisaris",
			KPI:                "Jumlah rapat koordinasi berkala dan pelaporan evaluasi dengan Komite Audit",
			Unit:               "Amount",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "4", "Q2": "4", "Q3": "4", "Q4": "4"},
			KPIActuals:         map[string]string{"Q1": "4", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menyampaikan laporan berkala progres pelaksanaan PKAT dan temuan berisiko tinggi",
			Actual:             "4",
			Target:             "4",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA05",
			GoalID:             "G-001",
			StrategicObjective: "Pengawasan pencegahan benturan kepentingan dan kepatuhan deklarasi etik",
			KPI:                "Persentase kepatuhan penyerahan deklarasi benturan kepentingan tepat waktu",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "95", "2025": "98", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "96", "2025": "98", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit transparansi dan pengungkapan hubungan afiliasi pegawai dan manajemen",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA06",
			GoalID:             "G-001",
			StrategicObjective: "Penilaian implementasi prinsip Good Corporate Governance (GCG) perusahaan",
			KPI:                "Skor asesmen GCG tahunan korporasi oleh penilai independen",
			Unit:               "Score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "85.0", "2025": "87.5", "2026": "90.0", "2027": "92.0", "2028": "94.0"},
			KPIActuals:         map[string]string{"2024": "86.2", "2025": "88.0", "2026": "91.5", "2027": "", "2028": ""},
			InternalAuditSO:    "Memverifikasi bukti pemenuhan parameter GCG di seluruh direktorat",
			Actual:             "91.5",
			Target:             "90.0",
			Calculation:        "101.67%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA07",
			GoalID:             "G-001",
			StrategicObjective: "Pengawasan keselarasan tata kelola pada anak perusahaan dan afiliasi",
			KPI:                "Persentase anak perusahaan yang telah diaudit keselarasan tata kelolanya",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80", "2025": "85", "2026": "90", "2027": "95", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "75", "2025": "82", "2026": "88", "2027": "", "2028": ""},
			InternalAuditSO:    "Meninjau penerapan pedoman grup holding pada entitas operasional anak perusahaan",
			Actual:             "88",
			Target:             "90",
			Calculation:        "97.78%",
			Status:             "Moderate",
		},
		{
			Code:               "SO-IA08",
			GoalID:             "G-001",
			StrategicObjective: "Keterbukaan informasi dan transparansi pelaporan berkala kepada publik/regulator",
			KPI:                "Keterlambatan pelaporan keterbukaan informasi material ke otoritas (hari kerja)",
			Unit:               "Day",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "0", "Q2": "0", "Q3": "0", "Q4": "0"},
			KPIActuals:         map[string]string{"Q1": "0", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menguji kepatuhan jadwal pelaporan publik dan kepatuhan keterbukaan informasi IDX",
			Actual:             "0",
			Target:             "0",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA09",
			GoalID:             "G-001",
			StrategicObjective: "Efektivitas fungsi legal dan mitigasi klausul kontrak perjanjian bernilai material",
			KPI:                "Persentase review kepatuhan hukum atas kontrak bernilai di atas Rp 10 Miliar",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "90", "2025": "95", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "88", "2025": "94", "2026": "96", "2027": "", "2028": ""},
			InternalAuditSO:    "Memastikan klausul mitigasi risiko, klausul audit, dan dispute resolution terpenuhi",
			Actual:             "96",
			Target:             "100",
			Calculation:        "96.00%",
			Status:             "Moderate",
		},
		{
			Code:               "SO-IA10",
			GoalID:             "G-001",
			StrategicObjective: "Penguatan budaya kepatuhan dan integritas organisasi (Tone at the Top)",
			KPI:                "Indeks survei persepsi budaya integritas dan etika bisnis internal",
			Unit:               "Score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80.0", "2025": "83.0", "2026": "86.0", "2027": "89.0", "2028": "92.0"},
			KPIActuals:         map[string]string{"2024": "82.5", "2025": "84.0", "2026": "87.0", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengevaluasi komitmen kepemimpinan dan pemahaman pegawai terhadap kode etik",
			Actual:             "87.0",
			Target:             "86.0",
			Calculation:        "101.16%",
			Status:             "Good",
		},

		// =========================================================================
		// PILAR 2: ENTERPRISE RISK MANAGEMENT & RISK ASSESSMENT (GoalID: G-002) - SO-IA11 s/d SO-IA20
		// =========================================================================
		{
			Code:               "SO-IA11",
			GoalID:             "G-002",
			StrategicObjective: "Melakukan mitigasi terhadap risiko-risiko prioritas operasional dan keuangan",
			KPI:                "Tercapainya tingkat risiko residual sesuai target perusahaan",
			Unit:               "Score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "0.80", "2025": "0.83", "2026": "0.85", "2027": "0.87", "2028": "0.90"},
			KPIActuals:         map[string]string{"2024": "0.81", "2025": "0.83", "2026": "0.86", "2027": "", "2028": ""},
			InternalAuditSO:    "Melakukan mitigasi terhadap risiko-risiko prioritas operasional dan keuangan",
			Actual:             "0.86",
			Target:             "0.85",
			Calculation:        "101.18%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA12",
			GoalID:             "G-002",
			StrategicObjective: "Integrasi audit universe dengan Enterprise Risk Management (ERM) Register",
			KPI:                "Persentase entitas audit berisiko tinggi yang terliput dalam PKAT",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "100", "2025": "100", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "100", "2025": "100", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Memastikan seluruh unit kerja kategori High Risk tercakup dalam jadwal penugasan audit",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA13",
			GoalID:             "G-002",
			StrategicObjective: "Melakukan asesmen ulang terhadap indikator risiko utama (Key Risk Indicators)",
			KPI:                "Ketepatan dan akurasi penetapan ambang batas Key Risk Indicators (KRI)",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "75", "2025": "80", "2026": "85", "2027": "90", "2028": "95"},
			KPIActuals:         map[string]string{"2024": "77", "2025": "81", "2026": "86", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengevaluasi kalibrasi KRI operasional cabang dan kantor pusat secara kuartalan",
			Actual:             "86",
			Target:             "85",
			Calculation:        "101.18%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA14",
			GoalID:             "G-002",
			StrategicObjective: "Pengawasan pengelolaan risiko kredit dan pembiayaan bermasalah",
			KPI:                "Rasio Non-Performing Loan / Financing (NPL) gross di bawah batas toleransi",
			Unit:               "%",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "2.5", "Q2": "2.5", "Q3": "2.4", "Q4": "2.3"},
			KPIActuals:         map[string]string{"Q1": "2.1", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menguji kepatuhan underwriting kredit dan kecukupan jaminan debitur besar",
			Actual:             "2.1",
			Target:             "2.5",
			Calculation:        "119.05%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA15",
			GoalID:             "G-002",
			StrategicObjective: "Pengawasan pengelolaan risiko likuiditas dan rasio kecukupan modal",
			KPI:                "Pemenuhan rasio Liquidity Coverage Ratio (LCR) di atas batas minimum",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "120", "Q2": "120", "Q3": "120", "Q4": "120"},
			KPIActuals:         map[string]string{"Q1": "135", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Memverifikasi keakuratan perhitungan cadangan kas primer dan sekunder",
			Actual:             "135",
			Target:             "120",
			Calculation:        "112.50%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA16",
			GoalID:             "G-002",
			StrategicObjective: "Evaluasi efektivitas rencana pemulihan bencana (Business Continuity & Disaster Recovery)",
			KPI:                "Frekuensi simulasi uji coba BCP/DRP tahunan yang berhasil memenuhi RTO dan RPO",
			Unit:               "Amount",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "1", "2025": "2", "2026": "2", "2027": "2", "2028": "2"},
			KPIActuals:         map[string]string{"2024": "1", "2025": "2", "2026": "2", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit kesiapan infrastruktur alternatif dan keandalan replikasi data DR Center",
			Actual:             "2",
			Target:             "2",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA17",
			GoalID:             "G-002",
			StrategicObjective: "Pengawasan risiko proyek strategis dan investasi modal (Capex Risk Assurance)",
			KPI:                "Persentase proyek strategis dengan nilai > Rp 20 Miliar yang diaudit tahapannya",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80", "2025": "85", "2026": "90", "2027": "95", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "75", "2025": "80", "2026": "85", "2027": "", "2028": ""},
			InternalAuditSO:    "Melakukan post-implementation review dan audit milestone proyek investasi",
			Actual:             "85",
			Target:             "90",
			Calculation:        "94.44%",
			Status:             "Moderate",
		},
		{
			Code:               "SO-IA18",
			GoalID:             "G-002",
			StrategicObjective: "Kesesuaian penerapan Risk Appetite Statement (RAS) di seluruh unit kerja",
			KPI:                "Tingkat deviasi indikator operasional terhadap batas toleransi risiko (RAS Breach)",
			Unit:               "Amount",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "1", "Q2": "1", "Q3": "0", "Q4": "0"},
			KPIActuals:         map[string]string{"Q1": "0", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Memeriksa kepatuhan parameter risiko limit eksposur trading dan operasional",
			Actual:             "0",
			Target:             "1",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA19",
			GoalID:             "G-002",
			StrategicObjective: "Pengawasan kualitas profil risiko operasional jaringan kantor cabang",
			KPI:                "Rata-rata skor audit kepatuhan risiko operasional kantor cabang",
			Unit:               "Score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80.0", "2025": "82.5", "2026": "85.0", "2027": "87.5", "2028": "90.0"},
			KPIActuals:         map[string]string{"2024": "81.0", "2025": "83.2", "2026": "86.1", "2027": "", "2028": ""},
			InternalAuditSO:    "Melakukan audit tematik terhadap cabang berkinerja risiko di bawah rata-rata",
			Actual:             "86.1",
			Target:             "85.0",
			Calculation:        "101.29%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA20",
			GoalID:             "G-002",
			StrategicObjective: "Validasi pengujian model estimasi risiko internal (Risk Model Validation)",
			KPI:                "Persentase model kuantitatif risiko yang telah divalidasi independen per tahun",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80", "2025": "85", "2026": "90", "2027": "95", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "80", "2025": "85", "2026": "92", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji keandalan asumsi, backtesting data, dan metodologi scoring risiko",
			Actual:             "92",
			Target:             "90",
			Calculation:        "102.22%",
			Status:             "Good",
		},

		// =========================================================================
		// PILAR 3: PENGENDALIAN INTERNAL & PELAPORAN KEUANGAN (GoalID: G-003) - SO-IA21 s/d SO-IA30
		// =========================================================================
		{
			Code:               "SO-IA21",
			GoalID:             "G-003",
			StrategicObjective: "Efektivitas sistem pengendalian internal atas pelaporan keuangan (ICFR)",
			KPI:                "Persentase pengujian desain dan efektivitas pengendalian kunci (Key Controls ICFR)",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "90", "2025": "95", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "92", "2025": "96", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji sampel pengendalian manual dan otomatis pada siklus akuntansi utama",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA22",
			GoalID:             "G-003",
			StrategicObjective: "Ketepatan waktu dan akurasi rekonsiliasi rekening perantara dan saldo bank",
			KPI:                "Persentase pos rekening perantara yang terselesaikan rekonsiliasinya < 7 hari",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "95", "Q2": "95", "Q3": "98", "Q4": "98"},
			KPIActuals:         map[string]string{"Q1": "97", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Memverifikasi saldo outstanding rekening un-reconciled dan pos menggantung",
			Actual:             "97",
			Target:             "95",
			Calculation:        "102.11%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA23",
			GoalID:             "G-003",
			StrategicObjective: "Kepatuhan terhadap Standar Akuntansi Keuangan (PSAK/IFRS) terkini",
			KPI:                "Jumlah temuan penyesuaian audit signifikan oleh Auditor Eksternal (KAP)",
			Unit:               "Amount",
			HibHig:             "HIB",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "2", "2025": "1", "2026": "0", "2027": "0", "2028": "0"},
			KPIActuals:         map[string]string{"2024": "1", "2025": "0", "2026": "0", "2027": "", "2028": ""},
			InternalAuditSO:    "Melakukan pre-audit atas penyusunan laporan keuangan tahunan sebelum audit KAP",
			Actual:             "0",
			Target:             "0",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA24",
			GoalID:             "G-003",
			StrategicObjective: "Akurasi pembentukan Cadangan Kerugian Penurunan Nilai (CKPN) berbasis PSAK 71",
			KPI:                "Tingkat deviasi perhitungan model Expected Credit Loss (ECL) terhadap realisasi kerugian",
			Unit:               "%",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "5.0", "Q2": "5.0", "Q3": "4.5", "Q4": "4.0"},
			KPIActuals:         map[string]string{"Q1": "4.2", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menguji integritas data staging aset keuangan dan probabilitas default (PD)",
			Actual:             "4.2",
			Target:             "5.0",
			Calculation:        "119.05%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA25",
			GoalID:             "G-003",
			StrategicObjective: "Pengawasan kepatuhan perpajakan korporasi dan mitigasi denda pajak",
			KPI:                "Persentase pelaporan dan penyetoran SPT masa dan tahunan tepat waktu",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "100", "2025": "100", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "100", "2025": "100", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji rekonsiliasi fiskal dan pemotongan PPh Pasal 21, 23, 4(2), serta PPN",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA26",
			GoalID:             "G-003",
			StrategicObjective: "Pengendalian transaksi dengan pihak berelasi (Related Party Transactions)",
			KPI:                "Persentase transaksi pihak berelasi yang memiliki kewajaran harga (Arm's Length)",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "95", "2025": "98", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "94", "2025": "97", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji kelayakan studi transfer pricing dan persetujuan dewan komisaris",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA27",
			GoalID:             "G-003",
			StrategicObjective: "Pengendalian pengelolaan kas kecil dan transaksi pembayaran vendor",
			KPI:                "Persentase pengeluaran kas yang didukung bukti transaksi otentik dan valid",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "98", "Q2": "98", "Q3": "99", "Q4": "100"},
			KPIActuals:         map[string]string{"Q1": "99", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Melakukan cash opname mendadak dan pengujian sampling invoice disbursement",
			Actual:             "99",
			Target:             "98",
			Calculation:        "101.02%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA28",
			GoalID:             "G-003",
			StrategicObjective: "Akurasi pencatatan aset tetap dan pelaksanaan sensus inventaris tahunan",
			KPI:                "Persentase aset tetap bernilai buku aktif yang terverifikasi keberadaan fisiknya",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "92", "2025": "95", "2026": "98", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "90", "2025": "94", "2026": "96", "2027": "", "2028": ""},
			InternalAuditSO:    "Melakukan uji petik inventarisasi fisik aset tetap kantor pusat dan unit operasional",
			Actual:             "96",
			Target:             "98",
			Calculation:        "97.96%",
			Status:             "Moderate",
		},
		{
			Code:               "SO-IA29",
			GoalID:             "G-003",
			StrategicObjective: "Pengawasan pengendalian piutang usaha dan penagihan (Aging Accounts Receivable)",
			KPI:                "Rasio piutang macet (> 90 hari) terhadap total piutang bruto",
			Unit:               "%",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "4.0", "Q2": "3.8", "Q3": "3.5", "Q4": "3.0"},
			KPIActuals:         map[string]string{"Q1": "3.2", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menguji verifikasi faktur piutang dan kepatuhan prosedur penagihan debitur",
			Actual:             "3.2",
			Target:             "4.0",
			Calculation:        "125.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA30",
			GoalID:             "G-003",
			StrategicObjective: "Validitas pengakuan beban akrual dan estimasi liabilitas kontinjensi",
			KPI:                "Tingkat ketepatan estimasi beban akrual dibandingkan realisasi pembayaran invoice",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "90", "2025": "92", "2026": "95", "2027": "97", "2028": "98"},
			KPIActuals:         map[string]string{"2024": "89", "2025": "93", "2026": "96", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit cutoff transaksi akhir tahun dan keabsahan pencatatan unbilled invoices",
			Actual:             "96",
			Target:             "95",
			Calculation:        "101.05%",
			Status:             "Good",
		},

		// =========================================================================
		// PILAR 4: TEKNOLOGI INFORMASI, CYBER SECURITY & DATA PRIVACY (GoalID: G-004) - SO-IA31 s/d SO-IA40
		// =========================================================================
		{
			Code:               "SO-IA31",
			GoalID:             "G-004",
			StrategicObjective: "Audit keamanan siber dan uji penetrasi berkala (Vulnerability & Pen-Test)",
			KPI:                "Persentase temuan kerentanan sistem kategori High & Critical yang ditutup < 14 hari",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "95", "Q2": "95", "Q3": "100", "Q4": "100"},
			KPIActuals:         map[string]string{"Q1": "96", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Melakukan verifikasi independen atas hasil remedi uji penetrasi aplikasi dan server",
			Actual:             "96",
			Target:             "95",
			Calculation:        "101.05%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA32",
			GoalID:             "G-004",
			StrategicObjective: "Kepatuhan terhadap Undang-Undang Perlindungan Data Pribadi (UU PDP)",
			KPI:                "Tingkat kepatuhan tata kelola pemrosesan data pribadi nasabah dan karyawan",
			Unit:               "score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "75.0", "2025": "85.0", "2026": "90.0", "2027": "95.0", "2028": "98.0"},
			KPIActuals:         map[string]string{"2024": "78.0", "2025": "86.5", "2026": "91.0", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit persetujuan pemrosesan data (consent), enkripsi data, dan hak subjek data",
			Actual:             "91.0",
			Target:             "90.0",
			Calculation:        "101.11%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA33",
			GoalID:             "G-004",
			StrategicObjective: "Pengendalian manajemen hak akses istimewa (Privileged Access Management / PAM)",
			KPI:                "Persentase pencabutan hak akses pegawai mutasi / resign dalam waktu < 24 jam",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "100", "Q2": "100", "Q3": "100", "Q4": "100"},
			KPIActuals:         map[string]string{"Q1": "100", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Melakukan rekonsiliasi berkala database Active Directory dengan data resign HR",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA34",
			GoalID:             "G-004",
			StrategicObjective: "Evaluasi tata kelola IT berbasis standar internasional (ISO 27001 / COBIT)",
			KPI:                "Tingkat kesesuaian kontrol keamanan informasi terhadap standar ISO 27001",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80", "2025": "85", "2026": "90", "2027": "95", "2028": "98"},
			KPIActuals:         map[string]string{"2024": "82", "2025": "87", "2026": "92", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit implementasi Information Security Management System (ISMS) tahunan",
			Actual:             "92",
			Target:             "90",
			Calculation:        "102.22%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA35",
			GoalID:             "G-004",
			StrategicObjective: "Pengujian integritas data backup dan kesiapan failover server kritis",
			KPI:                "Rasio keberhasilan pengujian restore data backup bulanan database core sistem",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "100", "Q2": "100", "Q3": "100", "Q4": "100"},
			KPIActuals:         map[string]string{"Q1": "100", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menyaksikan langsung prosedur recovery data uji petik rekaman backup pita/cloud",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA36",
			GoalID:             "G-004",
			StrategicObjective: "Pengawasan siklus pengembangan aplikasi dan software (SDLC Security Audit)",
			KPI:                "Persentase aplikasi baru yang telah melalui security gate check sebelum go-live",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "90", "2025": "95", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "88", "2025": "92", "2026": "97", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji dokumentasi code review, static code analysis (SAST), dan User Acceptance Test",
			Actual:             "97",
			Target:             "100",
			Calculation:        "97.00%",
			Status:             "Moderate",
		},
		{
			Code:               "SO-IA37",
			GoalID:             "G-004",
			StrategicObjective: "Pengendalian risiko integrasi API dan layanan pihak ketiga (Third-Party Cloud/API)",
			KPI:                "Persentase mitra integrasi API yang lolos asesmen kepatuhan keamanan teknis",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "85", "2025": "90", "2026": "95", "2027": "98", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "86", "2025": "91", "2026": "95", "2027": "", "2028": ""},
			InternalAuditSO:    "Memeriksa sertifikat digital, mekanisme token autentikasi, dan enkripsi payload API",
			Actual:             "95",
			Target:             "95",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA38",
			GoalID:             "G-004",
			StrategicObjective: "Audit manajemen patch keamanan sistem operasi dan database infrastruktur",
			KPI:                "Persentase server produksi yang terpasang patch keamanan kritis < 30 hari rilis",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "90", "Q2": "90", "Q3": "95", "Q4": "95"},
			KPIActuals:         map[string]string{"Q1": "88", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Melakukan scan independen terhadap riwayat patching dan end-of-life hardware",
			Actual:             "88",
			Target:             "90",
			Calculation:        "97.78%",
			Status:             "Moderate",
		},
		{
			Code:               "SO-IA39",
			GoalID:             "G-004",
			StrategicObjective: "Kecepatan respons penanganan insiden keamanan informasi (Cyber Incident Response)",
			KPI:                "Rata-rata waktu tanggap (Mean Time to Respond / MTTR) terhadap peringatan SIEM (jam)",
			Unit:               "Hour",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "2.0", "Q2": "1.8", "Q3": "1.5", "Q4": "1.0"},
			KPIActuals:         map[string]string{"Q1": "1.2", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menguji keandalan monitoring Security Operation Center (SOC) dan eskalasi alert",
			Actual:             "1.2",
			Target:             "2.0",
			Calculation:        "166.67%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA40",
			GoalID:             "G-004",
			StrategicObjective: "Pengawasan kepatuhan arsitektur cloud dan konfigurasi bucket penyimpanan data",
			KPI:                "Jumlah temuan bucket cloud atau repositori kode dengan konfigurasi public open",
			Unit:               "Amount",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "0", "Q2": "0", "Q3": "0", "Q4": "0"},
			KPIActuals:         map[string]string{"Q1": "0", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Melakukan automated audit terhadap Cloud Security Posture Management (CSPM)",
			Actual:             "0",
			Target:             "0",
			Calculation:        "100.00%",
			Status:             "Good",
		},

		// =========================================================================
		// PILAR 5: EFISIENSI OPERASIONAL & SUPPLY CHAIN (GoalID: G-005) - SO-IA41 s/d SO-IA50
		// =========================================================================
		{
			Code:               "SO-IA41",
			GoalID:             "G-005",
			StrategicObjective: "Meningkatkan efisiensi dan pengendalian beban operasional (BOPO)",
			KPI:                "Rasio biaya operasional terhadap pendapatan operasional (BOPO)",
			Unit:               "%",
			HibHig:             "HIB",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "64.0", "2025": "63.0", "2026": "62.3", "2027": "61.5", "2028": "61.0"},
			KPIActuals:         map[string]string{"2024": "63.8", "2025": "62.7", "2026": "62.0", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengidentifikasi pos pemborosan anggaran dan potensi efisiensi proses kerja",
			Actual:             "62.0",
			Target:             "62.3",
			Calculation:        "100.48%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA42",
			GoalID:             "G-005",
			StrategicObjective: "Efisiensi dan transparansi pengadaan barang dan jasa via e-Procurement",
			KPI:                "Persentase pengadaan barang/jasa yang menggunakan sistem katalog elektronik",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "75", "2025": "80", "2026": "85", "2027": "90", "2028": "95"},
			KPIActuals:         map[string]string{"2024": "78", "2025": "83", "2026": "88", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji kepatuhan penunjukan langsung dan pengadaan tender terbuka",
			Actual:             "88",
			Target:             "85",
			Calculation:        "103.53%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA43",
			GoalID:             "G-005",
			StrategicObjective: "Pengendalian kepatuhan pemenuhan Service Level Agreement (SLA) vendor utama",
			KPI:                "Persentase vendor strategis yang memenuhi standar SLA kontrak",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "90", "Q2": "90", "Q3": "95", "Q4": "95"},
			KPIActuals:         map[string]string{"Q1": "92", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Mengaudit penerapan sanksi penalti atas keterlambatan kinerja rekanan",
			Actual:             "92",
			Target:             "90",
			Calculation:        "102.22%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA44",
			GoalID:             "G-005",
			StrategicObjective: "Pengendalian selisih stok persediaan dan susut barang (Inventory Shrinkage)",
			KPI:                "Rasio selisih susut persediaan gudang terhadap total nilai persediaan rata-rata",
			Unit:               "%",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "0.5", "Q2": "0.5", "Q3": "0.4", "Q4": "0.3"},
			KPIActuals:         map[string]string{"Q1": "0.3", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Melakukan uji petik stock opname fisik gudang dan verifikasi kartu stok",
			Actual:             "0.3",
			Target:             "0.5",
			Calculation:        "166.67%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA45",
			GoalID:             "G-005",
			StrategicObjective: "Optimalisasi tingkat utilisasi aset gedung, kendaraan, dan sarana operasional",
			KPI:                "Persentase tingkat utilisasi aset produktif perusahaan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "75", "2025": "80", "2026": "85", "2027": "88", "2028": "90"},
			KPIActuals:         map[string]string{"2024": "74", "2025": "79", "2026": "83", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit efektivitas biaya sewa dan rencana pelepasan aset non-produktif (idle)",
			Actual:             "83",
			Target:             "85",
			Calculation:        "97.65%",
			Status:             "Moderate",
		},
		{
			Code:               "SO-IA46",
			GoalID:             "G-005",
			StrategicObjective: "Percepatan siklus waktu layanan pelanggan inti (Turnaround Time / TAT)",
			KPI:                "Rata-rata waktu proses persetujuan layanan operasional standar (hari kerja)",
			Unit:               "Day",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "3.0", "Q2": "2.8", "Q3": "2.5", "Q4": "2.0"},
			KPIActuals:         map[string]string{"Q1": "2.4", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menganalisis bottleneck proses verifikasi berkas dan persetujuan bertingkat",
			Actual:             "2.4",
			Target:             "3.0",
			Calculation:        "125.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA47",
			GoalID:             "G-005",
			StrategicObjective: "Kepatuhan SOP pengelolaan logistik distribusi dan armada ekspedisi",
			KPI:                "Tingkat ketepatan waktu pengiriman barang dan keutuhan paket logistik",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "95", "Q2": "95", "Q3": "98", "Q4": "98"},
			KPIActuals:         map[string]string{"Q1": "96", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Mengaudit rute perjalanan armada, biaya bahan bakar, dan klaim kerusakan transit",
			Actual:             "96",
			Target:             "95",
			Calculation:        "101.05%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA48",
			GoalID:             "G-005",
			StrategicObjective: "Pengawasan penghematan konsumsi utilitas dan biaya umum kantor (Overhead Costs)",
			KPI:                "Realisasi penghematan beban listrik, air, dan ATK terhadap pagu anggaran",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "5", "2025": "7", "2026": "10", "2027": "12", "2028": "15"},
			KPIActuals:         map[string]string{"2024": "6", "2025": "8", "2026": "11", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengevaluasi program efisiensi energi kantor dan digitalisasi arsip dokumen",
			Actual:             "11",
			Target:             "10",
			Calculation:        "110.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA49",
			GoalID:             "G-005",
			StrategicObjective: "Otomasi dan digitalisasi alur kerja dokumen persetujuan operasional",
			KPI:                "Persentase proses administrasi rutin yang telah terintegrasi tanda tangan digital",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "60", "2025": "75", "2026": "85", "2027": "95", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "65", "2025": "80", "2026": "90", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji keabsahan hukum e-signature dan audit log approval transaksi",
			Actual:             "90",
			Target:             "85",
			Calculation:        "105.88%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA50",
			GoalID:             "G-005",
			StrategicObjective: "Evaluasi pengelolaan kontrak sewa tempat usaha dan renewal jangka panjang",
			KPI:                "Persentase review legalitas perpanjangan sewa sebelum jatuh tempo 6 bulan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "85", "2025": "90", "2026": "95", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "82", "2025": "88", "2026": "94", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit kewajaran harga sewa pembanding pasar dan negosiasi klausul eskalasi",
			Actual:             "94",
			Target:             "95",
			Calculation:        "98.95%",
			Status:             "Moderate",
		},

		// =========================================================================
		// PILAR 6: KEPATUHAN REGULASI & ANTI-FINANCIAL CRIME (GoalID: G-006) - SO-IA51 s/d SO-IA60
		// =========================================================================
		{
			Code:               "SO-IA51",
			GoalID:             "G-006",
			StrategicObjective: "Kepatuhan program Anti-Pencucian Uang & Pencegahan Pendanaan Terorisme (APU-PPT)",
			KPI:                "Tingkat kesesuaian penerapan 5 pilar program APU-PPT sesuai regulasi PPATK/OJK",
			Unit:               "score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "85.0", "2025": "88.0", "2026": "90.0", "2027": "93.0", "2028": "95.0"},
			KPIActuals:         map[string]string{"2024": "86.0", "2025": "89.0", "2026": "92.0", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji kepatuhan CDD, EDD, pemutakhiran data nasabah, dan pelatihan pegawai",
			Actual:             "92.0",
			Target:             "90.0",
			Calculation:        "102.22%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA52",
			GoalID:             "G-006",
			StrategicObjective: "Ketepatan waktu pelaporan Laporan Transaksi Keuangan Mencurigakan (LTKM ke PPATK)",
			KPI:                "Persentase laporan LTKM yang disampaikan dalam waktu < 3 hari kerja sejak teridentifikasi",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "100", "Q2": "100", "Q3": "100", "Q4": "100"},
			KPIActuals:         map[string]string{"Q1": "100", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Mengaudit parameter transaksi mencurigakan dan keandalan sistem pelaporan goAML",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA53",
			GoalID:             "G-006",
			StrategicObjective: "Pengawasan penyaringan daftar sanksi internasional dan terorisme (PEP & Sanction Screening)",
			KPI:                "Rasio kegagalan penyaringan database nama nasabah baru terhadap daftar DTTOT/DPSP",
			Unit:               "%",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "0.0", "Q2": "0.0", "Q3": "0.0", "Q4": "0.0"},
			KPIActuals:         map[string]string{"Q1": "0.0", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Melakukan pengujian penetrasi algoritma fuzzy logic nama nasabah dan PEP alert",
			Actual:             "0.0",
			Target:             "0.0",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA54",
			GoalID:             "G-006",
			StrategicObjective: "Kepatuhan terhadap regulasi Perlindungan Konsumen dan Market Conduct OJK",
			KPI:                "Persentase pengaduan nasabah yang diselesaikan sesuai batas waktu SLA regulasi",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "95", "Q2": "95", "Q3": "98", "Q4": "98"},
			KPIActuals:         map[string]string{"Q1": "96", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menguji transparansi informasi produk, ringkasan informasi produk, dan hotline klaim",
			Actual:             "96",
			Target:             "95",
			Calculation:        "101.05%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA55",
			GoalID:             "G-006",
			StrategicObjective: "Kepatuhan terhadap ketentuan Batas Maksimum Pemberian Kredit (BMPK / Legal Lending Limit)",
			KPI:                "Jumlah pelanggaran atau pelampauan BMPK pada pihak terkait dan debitur grup",
			Unit:               "Amount",
			HibHig:             "HIB",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "0", "2025": "0", "2026": "0", "2027": "0", "2028": "0"},
			KPIActuals:         map[string]string{"2024": "0", "2025": "0", "2026": "0", "2027": "", "2028": ""},
			InternalAuditSO:    "Memverifikasi konsolidasi modal tier 1 dan aglomerasi debitur grup terafiliasi",
			Actual:             "0",
			Target:             "0",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA56",
			GoalID:             "G-006",
			StrategicObjective: "Kepatuhan standar Keselamatan dan Kesehatan Kerja (K3) serta Lingkungan Kerja",
			KPI:                "Tingkat pemenuhan audit sertifikasi SMK3 di seluruh fasilitas operasional utama",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "85", "2025": "90", "2026": "95", "2027": "98", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "87", "2025": "92", "2026": "96", "2027": "", "2028": ""},
			InternalAuditSO:    "Menginspeksi kelayakan sertifikasi alat berat, jalur evakuasi, dan APAR berkala",
			Actual:             "96",
			Target:             "95",
			Calculation:        "101.05%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA57",
			GoalID:             "G-006",
			StrategicObjective: "Pengawasan kepatuhan izin usaha operasional dan perpanjangan lisensi regulasi",
			KPI:                "Persentase perizinan usaha aktif yang diperpanjang sebelum masa berlaku habis",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "100", "2025": "100", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "100", "2025": "100", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit matriks perizinan OSS, izin kantor cabang, dan izin penunjang bisnis",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA58",
			GoalID:             "G-006",
			StrategicObjective: "Kepatuhan ketentuan anti-monopoli dan persaingan usaha sehat (KPPU)",
			KPI:                "Jumlah pengaduan atau investigasi persaingan usaha yang terkonfirmasi pelanggaran",
			Unit:               "Amount",
			HibHig:             "HIB",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "0", "2025": "0", "2026": "0", "2027": "0", "2028": "0"},
			KPIActuals:         map[string]string{"2024": "0", "2025": "0", "2026": "0", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji perjanjian eksklusivitas vendor, tender bidding, dan kebijakan penentuan harga",
			Actual:             "0",
			Target:             "0",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA59",
			GoalID:             "G-006",
			StrategicObjective: "Kecepatan tindak lanjut pemenuhan komitmen hasil pemeriksaan regulator (OJK/BI)",
			KPI:                "Persentase komitmen tindak lanjut matriks audit OJK yang tuntas tepat waktu",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "100", "Q2": "100", "Q3": "100", "Q4": "100"},
			KPIActuals:         map[string]string{"Q1": "100", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Melakukan pre-validation bukti dokumen sebelum disampaikan ke pengawas otoritas",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA60",
			GoalID:             "G-006",
			StrategicObjective: "Pemantauan kepatuhan penerapan regulasi baru yang diterbitkan (Regulatory Horizon Scanning)",
			KPI:                "Persentase regulasi baru yang telah selesai dilakukan gap analysis dalam 60 hari",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "90", "2025": "95", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "88", "2025": "94", "2026": "98", "2027": "", "2028": ""},
			InternalAuditSO:    "Memastikan penyesuaian SOP dan kesiapan sistem sebelum tanggal efektif regulasi",
			Actual:             "98",
			Target:             "100",
			Calculation:        "98.00%",
			Status:             "Moderate",
		},

		// =========================================================================
		// PILAR 7: ANTI-FRAUD, ETIKA & FORENSIK (GoalID: G-007) - SO-IA61 s/d SO-IA70
		// =========================================================================
		{
			Code:               "SO-IA61",
			GoalID:             "G-007",
			StrategicObjective: "Implementasi 4 pilar Strategi Anti-Fraud (SAF) secara komprehensif",
			KPI:                "Skor evaluasi efektivitas sistem pencegahan dan mitigasi fraud internal",
			Unit:               "score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80.0", "2025": "83.0", "2026": "86.0", "2027": "89.0", "2028": "92.0"},
			KPIActuals:         map[string]string{"2024": "82.0", "2025": "85.0", "2026": "88.0", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji pilar pencegahan, deteksi, investigasi-sanksi, serta evaluasi fraud",
			Actual:             "88.0",
			Target:             "86.0",
			Calculation:        "102.33%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA62",
			GoalID:             "G-007",
			StrategicObjective: "Kecepatan penyelesaian audit investigasi atas dugaan kecurangan (Fraud Investigation)",
			KPI:                "Rata-rata waktu penyelesaian Laporan Hasil Investigasi (LHI) sejak penugasan (hari)",
			Unit:               "Day",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "30", "Q2": "30", "Q3": "25", "Q4": "20"},
			KPIActuals:         map[string]string{"Q1": "22", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Mempercepat proses digital forensics, pengumpulan barang bukti, dan klarifikasi saksi",
			Actual:             "22",
			Target:             "30",
			Calculation:        "136.36%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA63",
			GoalID:             "G-007",
			StrategicObjective: "Deteksi dini fraud melalui pemanfaatan continuous transaction monitoring (Fraud Analytics)",
			KPI:                "Persentase kasus anomali transaksi yang terdeteksi secara otomatis via analitik data",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "50", "2025": "60", "2026": "70", "2027": "80", "2028": "85"},
			KPIActuals:         map[string]string{"2024": "52", "2025": "64", "2026": "74", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengembangkan query deteksi red-flags transaksi akhir pekan, split order, dan double payment",
			Actual:             "74",
			Target:             "70",
			Calculation:        "105.71%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA64",
			GoalID:             "G-007",
			StrategicObjective: "Pelaksanaan Fraud Risk Assessment (FRA) pada unit kerja dan proses bisnis berisiko tinggi",
			KPI:                "Cakupan asesmen risiko kecurangan pada proses operasional kunci tahun berjalan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80", "2025": "85", "2026": "90", "2027": "95", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "80", "2025": "86", "2026": "91", "2027": "", "2028": ""},
			InternalAuditSO:    "Memetakan skenario fraud, motivasi, peluang, dan rasionalisasi pada siklus pengadaan & kas",
			Actual:             "91",
			Target:             "90",
			Calculation:        "101.11%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA65",
			GoalID:             "G-007",
			StrategicObjective: "Optimalisasi pemulihan kerugian aset perusahaan akibat tindak pidana fraud (Asset Recovery)",
			KPI:                "Persentase nilai pemulihan kerugian finansial dari kasus fraud yang telah vonis inkrah",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "60", "2025": "65", "2026": "70", "2027": "75", "2028": "80"},
			KPIActuals:         map[string]string{"2024": "62", "2025": "67", "2026": "72", "2027": "", "2028": ""},
			InternalAuditSO:    "Berkoordinasi dengan tim legal dan aparat penegak hukum untuk penelusuran aset pelaku",
			Actual:             "72",
			Target:             "70",
			Calculation:        "102.86%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA66",
			GoalID:             "G-007",
			StrategicObjective: "Peningkatan kesadaran dan literasi anti-fraud karyawan (Fraud Awareness Training)",
			KPI:                "Persentase karyawan tetap yang telah menyelesaikan e-learning anti-fraud tahunan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "90", "2025": "95", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "92", "2025": "96", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Memverifikasi daftar kelulusan pre-test dan post-test modul anti-fraud seluruh divisi",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA67",
			GoalID:             "G-007",
			StrategicObjective: "Kepatuhan prosedur uji tuntas latar belakang pegawai kunci (Pre-Employment Background Check)",
			KPI:                "Persentase rekrutmen posisi strategis yang telah melalui background screening lengkap",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "100", "Q2": "100", "Q3": "100", "Q4": "100"},
			KPIActuals:         map[string]string{"Q1": "100", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menguji kelayakan verifikasi ijazah, riwayat kredit SLIK, dan catatan hukum kandidat",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA68",
			GoalID:             "G-007",
			StrategicObjective: "Evaluasi pengendalian pemisahan tugas dan fungsi kritis (Segregation of Duties / SoD)",
			KPI:                "Jumlah konflik otorisasi user sistem ERP yang belum dimitigasi compensating controls",
			Unit:               "Amount",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "0", "Q2": "0", "Q3": "0", "Q4": "0"},
			KPIActuals:         map[string]string{"Q1": "0", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Menguji matriks SoD antara pembuat transaksi, pemeriksa, dan pembayar kas",
			Actual:             "0",
			Target:             "0",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA69",
			GoalID:             "G-007",
			StrategicObjective: "Pengawasan terhadap aktivitas rekening tidak aktif (Dormant Accounts Monitoring)",
			KPI:                "Persentase reaktivasi rekening dormant yang dilakukan sesuai verifikasi tatap muka",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "100", "Q2": "100", "Q3": "100", "Q4": "100"},
			KPIActuals:         map[string]string{"Q1": "100", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Mencegah pengalihan saldo rekening nasabah pasif oleh oknum pegawai internal",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA70",
			GoalID:             "G-007",
			StrategicObjective: "Pengendalian pencegahan penyuapan dan gratifikasi (ISO 37001 SMAP)",
			KPI:                "Tingkat kepatuhan deklarasi penerimaan/penolakan gratifikasi per semester",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "95", "2025": "98", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "96", "2025": "98", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit buku register gratifikasi Unit Pengendalian Gratifikasi (UPG)",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},

		// =========================================================================
		// PILAR 8: PENGEMBANGAN SDM & KOMPETENSI AUDITOR (GoalID: G-008) - SO-IA71 s/d SO-IA80
		// =========================================================================
		{
			Code:               "SO-IA71",
			GoalID:             "G-008",
			StrategicObjective: "Mengembangkan kompetensi dan profesionalisme internal auditor (CPE Training)",
			KPI:                "Rata-rata jam pelatihan profesional per auditor internal per tahun (minimal 40 jam)",
			Unit:               "Hour",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "40", "2025": "42", "2026": "45", "2027": "48", "2028": "50"},
			KPIActuals:         map[string]string{"2024": "42", "2025": "44", "2026": "46", "2027": "", "2028": ""},
			InternalAuditSO:    "Memfasilitasi keikutsertaan auditor dalam lokakarya IIA, OJK, dan sertifikasi profesi",
			Actual:             "46",
			Target:             "45",
			Calculation:        "102.22%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA72",
			GoalID:             "G-008",
			StrategicObjective: "Peningkatan jumlah auditor yang memiliki sertifikasi profesi nasional/internasional",
			KPI:                "Persentase staf audit yang memiliki sertifikasi profesional (CIA, CISA, QIA, CRMA, CFE)",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "50", "2025": "60", "2026": "70", "2027": "80", "2028": "85"},
			KPIActuals:         map[string]string{"2024": "55", "2025": "64", "2026": "73", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengembangkan kompetensi internal auditor",
			Actual:             "73",
			Target:             "70",
			Calculation:        "104.29%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA73",
			GoalID:             "G-008",
			StrategicObjective: "Retensi talenta audit dan perencanaan suksesi kepemimpinan audit (Talent Management)",
			KPI:                "Tingkat retensi tahunan staf audit internal dengan predikat kinerja memuaskan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "85", "2025": "88", "2026": "90", "2027": "92", "2028": "95"},
			KPIActuals:         map[string]string{"2024": "87", "2025": "89", "2026": "92", "2027": "", "2028": ""},
			InternalAuditSO:    "Menyusun jenjang karir audit yang jelas dan program rotasi transfer pengetahuan",
			Actual:             "92",
			Target:             "90",
			Calculation:        "102.22%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA74",
			GoalID:             "G-008",
			StrategicObjective: "Audit sistem penilaian kinerja karyawan dan transparansi remunerasi (KPI Management)",
			KPI:                "Persentase keselarasan penetapan KPI individu dengan corporate scorecard",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "90", "2025": "92", "2026": "95", "2027": "98", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "88", "2025": "93", "2026": "96", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji keadilan distribusi bonus kinerja dan kepatuhan sistem appraisal HR",
			Actual:             "96",
			Target:             "95",
			Calculation:        "101.05%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA75",
			GoalID:             "G-008",
			StrategicObjective: "Kepatuhan regulasi ketenagakerjaan, upah minimum, dan jaminan BPJS",
			KPI:                "Persentase kepatuhan pendaftaran dan pembayaran iuran BPJS Ketenagakerjaan & Kesehatan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "100", "2025": "100", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "100", "2025": "100", "2026": "100", "2027": "", "2028": ""},
			InternalAuditSO:    "Memeriksa rekonsiliasi data payroll bulanan dengan bukti setor bank penerima iuran",
			Actual:             "100",
			Target:             "100",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA76",
			GoalID:             "G-008",
			StrategicObjective: "Optimalisasi produktivitas dan alokasi jam kerja efektif auditor (Billable Audit Hours)",
			KPI:                "Rasio jam kerja langsung penugasan audit (direct audit hours) terhadap total jam kerja",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "75", "Q2": "75", "Q3": "80", "Q4": "80"},
			KPIActuals:         map[string]string{"Q1": "78", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Meminimalkan waktu beban administrasi non-audit melalui digitalisasi kertas kerja",
			Actual:             "78",
			Target:             "75",
			Calculation:        "104.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA77",
			GoalID:             "G-008",
			StrategicObjective: "Pengawasan pengelolaan program dana pensiun dan kewajiban imbalan pasca kerja",
			KPI:                "Tingkat kecukupan aktuarial pendanaan liabilitas pensiun (Funding Ratio)",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "95", "2025": "98", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "96", "2025": "99", "2026": "101", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji portofolio penempatan investasi dana pensiun dan asumsi laporan aktuaris",
			Actual:             "101",
			Target:             "100",
			Calculation:        "101.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA78",
			GoalID:             "G-008",
			StrategicObjective: "Audit efektivitas program onboarding dan masa percobaan karyawan baru (Probation Review)",
			KPI:                "Persentase pelaksanaan evaluasi kinerja probation sebelum batas akhir 3 bulan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "95", "Q2": "95", "Q3": "98", "Q4": "98"},
			KPIActuals:         map[string]string{"Q1": "97", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Mencegah pengangkatan status karyawan tetap tanpa dokumen penilaian objektif",
			Actual:             "97",
			Target:             "95",
			Calculation:        "102.11%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA79",
			GoalID:             "G-008",
			StrategicObjective: "Pengawasan kebijakan keberagaman, kesetaraan gender, dan inklusi (DEI Framework)",
			KPI:                "Indeks kesetaraan kesempatan berkarir dan kompensasi dalam survei kepuasan karyawan",
			Unit:               "score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80.0", "2025": "83.0", "2026": "85.0", "2027": "88.0", "2028": "90.0"},
			KPIActuals:         map[string]string{"2024": "81.0", "2025": "84.0", "2026": "86.5", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengaudit rasio keterwakilan dan pemenuhan hak perlindungan pekerja wanita",
			Actual:             "86.5",
			Target:             "85.0",
			Calculation:        "101.76%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA80",
			GoalID:             "G-008",
			StrategicObjective: "Audit kepatuhan jam kerja, lembur, dan manajemen beban kerja (Work-Life Balance)",
			KPI:                "Persentase kepatuhan persetujuan otorisasi lembur dan batas maksimum jam lembur bulanan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "95", "Q2": "95", "Q3": "98", "Q4": "98"},
			KPIActuals:         map[string]string{"Q1": "93", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Mencegah kelelahan kerja ekstrem dan kesalahan input klaim lembur manual",
			Actual:             "93",
			Target:             "95",
			Calculation:        "97.89%",
			Status:             "Moderate",
		},

		// =========================================================================
		// PILAR 9: ESG (ENVIRONMENTAL, SOCIAL, GOVERNANCE) & SUSTAINABILITY (GoalID: G-009) - SO-IA81 s/d SO-IA90
		// =========================================================================
		{
			Code:               "SO-IA81",
			GoalID:             "G-009",
			StrategicObjective: "Audit pelaporan keberlanjutan (Sustainability Reporting) sesuai POJK 51/POJK.03/2017",
			KPI:                "Tingkat kesesuaian data indikator kinerja ESG dalam Sustainability Report terhadap standar GRI",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80", "2025": "85", "2026": "90", "2027": "95", "2028": "98"},
			KPIActuals:         map[string]string{"2024": "82", "2025": "87", "2026": "92", "2027": "", "2028": ""},
			InternalAuditSO:    "Memverifikasi keabsahan kalkulasi data konsumsi emisi, energi, dan program CSR",
			Actual:             "92",
			Target:             "90",
			Calculation:        "102.22%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA82",
			GoalID:             "G-009",
			StrategicObjective: "Pengawasan penyaluran portofolio pembiayaan/investasi hijau (Green Financing Portfolio)",
			KPI:                "Persentase pemenuhan target portofolio kategori Kegiatan Usaha Berkelanjutan (KKUB)",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "10", "2025": "12", "2026": "15", "2027": "18", "2028": "20"},
			KPIActuals:         map[string]string{"2024": "11", "2025": "13", "2026": "16", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji uji tuntas lingkungan calon debitur pembiayaan proyek ramah lingkungan",
			Actual:             "16",
			Target:             "15",
			Calculation:        "106.67%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA83",
			GoalID:             "G-009",
			StrategicObjective: "Pengendalian pengelolaan limbah operasional dan jejak karbon (Carbon Footprint)",
			KPI:                "Persentase pengurangan intensitas emisi karbon (GHG Scope 1 & 2) terhadap baseline",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "3.0", "2025": "5.0", "2026": "7.5", "2027": "10.0", "2028": "12.5"},
			KPIActuals:         map[string]string{"2024": "3.5", "2025": "5.5", "2026": "8.0", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji kepatuhan penanganan limbah B3 dan audit meteran listrik energi terbarukan",
			Actual:             "8.0",
			Target:             "7.5",
			Calculation:        "106.67%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA84",
			GoalID:             "G-009",
			StrategicObjective: "Audit efektivitas program Tanggung Jawab Sosial dan Lingkungan (TJSL / CSR)",
			KPI:                "Persentase penyaluran dana TJSL yang sesuai target penerima manfaat dan regulasi",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "95", "2025": "98", "2026": "100", "2027": "100", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "94", "2025": "97", "2026": "99", "2027": "", "2028": ""},
			InternalAuditSO:    "Memverifikasi akuntabilitas pembukuan yayasan mitra pelaksana program pemberdayaan",
			Actual:             "99",
			Target:             "100",
			Calculation:        "99.00%",
			Status:             "Moderate",
		},
		{
			Code:               "SO-IA85",
			GoalID:             "G-009",
			StrategicObjective: "Kepatuhan rantai pasok terhadap standar hak asasi manusia dan etika kerja (Supply Chain ESG)",
			KPI:                "Persentase vendor strategis yang menandatangani Pakta Integritas dan Standar Etika ESG",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80", "2025": "85", "2026": "90", "2027": "95", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "82", "2025": "88", "2026": "93", "2027": "", "2028": ""},
			InternalAuditSO:    "Melakukan desktop audit kepatuhan anti-pekerja anak dan upah layak rekanan pengadaan",
			Actual:             "93",
			Target:             "90",
			Calculation:        "103.33%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA86",
			GoalID:             "G-009",
			StrategicObjective: "Audit inisiatif Paperless dan digitalisasi dokumentasi pengawasan internal audit",
			KPI:                "Persentase pengurangan konsumsi kertas di unit Internal Audit dibandingkan tahun dasar",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "50", "2025": "65", "2026": "80", "2027": "90", "2028": "95"},
			KPIActuals:         map[string]string{"2024": "55", "2025": "70", "2026": "85", "2027": "", "2028": ""},
			InternalAuditSO:    "Mengimplementasikan 100% electronic working paper (E-WP) dan cloud review",
			Actual:             "85",
			Target:             "80",
			Calculation:        "106.25%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA87",
			GoalID:             "G-009",
			StrategicObjective: "Pengawasan kepatuhan pengelolaan limbah medis / B3 operasional cabang",
			KPI:                "Jumlah surat peringatan dinas lingkungan hidup terkait pengelolaan limbah kantor",
			Unit:               "Amount",
			HibHig:             "HIB",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "0", "2025": "0", "2026": "0", "2027": "0", "2028": "0"},
			KPIActuals:         map[string]string{"2024": "0", "2025": "0", "2026": "0", "2027": "", "2028": ""},
			InternalAuditSO:    "Menguji kerja sama pengangkutan limbah dengan pihak ketiga berizin KLHK",
			Actual:             "0",
			Target:             "0",
			Calculation:        "100.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA88",
			GoalID:             "G-009",
			StrategicObjective: "Evaluasi efisiensi intensitas konsumsi air dan konservasi sumber daya air",
			KPI:                "Persentase penghematan konsumsi air per meter persegi gedung kantor",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "3.0", "2025": "4.0", "2026": "5.0", "2027": "6.0", "2028": "7.0"},
			KPIActuals:         map[string]string{"2024": "3.2", "2025": "4.5", "2026": "5.5", "2027": "", "2028": ""},
			InternalAuditSO:    "Menginspeksi sistem resapan air hujan dan sensor efisiensi sanitasi gedung",
			Actual:             "5.5",
			Target:             "5.0",
			Calculation:        "110.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA89",
			GoalID:             "G-009",
			StrategicObjective: "Asesmen risiko perubahan iklim terhadap ketahanan fisik aset kantor (Climate Risk Assessment)",
			KPI:                "Cakupan pemetaan risiko banjir dan bencana iklim terhadap lokasi cabang baru",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80", "2025": "85", "2026": "90", "2027": "95", "2028": "100"},
			KPIActuals:         map[string]string{"2024": "80", "2025": "85", "2026": "92", "2027": "", "2028": ""},
			InternalAuditSO:    "Memeriksa polis asuransi risiko bencana alam dan konstruksi pencegahan banjir",
			Actual:             "92",
			Target:             "90",
			Calculation:        "102.22%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA90",
			GoalID:             "G-009",
			StrategicObjective: "Peningkatan peringkat dan skor pemeringkatan keberlanjutan (ESG Rating Korporasi)",
			KPI:                "Skor penilaian ESG korporasi oleh lembaga pemeringkat independen",
			Unit:               "Score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "65.0", "2025": "70.0", "2026": "75.0", "2027": "80.0", "2028": "85.0"},
			KPIActuals:         map[string]string{"2024": "66.5", "2025": "72.0", "2026": "77.5", "2027": "", "2028": ""},
			InternalAuditSO:    "Menilai kesiapan dokumentasi verifikasi kriteria asesmen ESG indeks saham IDX ESG Leaders",
			Actual:             "77.5",
			Target:             "75.0",
			Calculation:        "103.33%",
			Status:             "Good",
		},

		// =========================================================================
		// PILAR 10: KUALITAS AUDIT, METODOLOGI & NILAI TAMBAH (GoalID: G-010) - SO-IA91 s/d SO-IA100
		// =========================================================================
		{
			Code:               "SO-IA91",
			GoalID:             "G-010",
			StrategicObjective: "Penyelesaian Rencana Audit Tahunan (PKAT / PKPT Completion Rate)",
			KPI:                "Persentase realisasi penugasan audit dibandingkan rencana PKAT tahun berjalan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "95", "Q2": "95", "Q3": "95", "Q4": "95"},
			KPIActuals:         map[string]string{"Q1": "97", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Tingkatkan efisiensi pelaksanaan audit tahunan",
			Actual:             "97",
			Target:             "95",
			Calculation:        "102.11%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA92",
			GoalID:             "G-010",
			StrategicObjective: "Ketepatan waktu penyampaian Laporan Hasil Audit (LHA Timeliness)",
			KPI:                "Rata-rata waktu penyampaian LHA setelah exit meeting (maksimal 14 hari kerja)",
			Unit:               "Day",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "14", "Q2": "14", "Q3": "12", "Q4": "10"},
			KPIActuals:         map[string]string{"Q1": "11", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Percepat penyampaian LHA ke pihak manajemen",
			Actual:             "11",
			Target:             "14",
			Calculation:        "127.27%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA93",
			GoalID:             "G-010",
			StrategicObjective: "Tingkat kepuasan auditee dan klien atas pelaksanaan audit (Auditee Satisfaction Index)",
			KPI:                "Skor survei kepuasan auditee terhadap profesionalisme dan nilai tambah rekomendasi",
			Unit:               "Score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "4.0", "2025": "4.2", "2026": "4.5", "2027": "4.8", "2028": "5.0"},
			KPIActuals:         map[string]string{"2024": "4.2", "2025": "4.5", "2026": "4.7", "2027": "", "2028": ""},
			InternalAuditSO:    "Tingkatkan kualitas layanan & rekomendasi audit",
			Actual:             "4.7",
			Target:             "4.5",
			Calculation:        "104.44%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA94",
			GoalID:             "G-010",
			StrategicObjective: "Penyelesaian tindak lanjut rekomendasi hasil audit (Action Plan Closed Rate)",
			KPI:                "Persentase temuan audit yang telah ditindaklanjuti auditee sesuai target waktu",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "90", "Q2": "90", "Q3": "90", "Q4": "90"},
			KPIActuals:         map[string]string{"Q1": "91", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Memastikan seluruh temuan audit ditindaklanjuti auditee",
			Actual:             "91",
			Target:             "90",
			Calculation:        "101.11%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA95",
			GoalID:             "G-010",
			StrategicObjective: "Monitoring progres penugasan audit bulanan (Monthly Audit Progress Monitoring)",
			KPI:                "Tingkat ketercapaian milestone tahapan fieldwork tepat waktu per bulan",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "90", "Q2": "90", "Q3": "90", "Q4": "90"},
			KPIActuals:         map[string]string{"Q1": "95", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Monitoring progres penyelesaian audit per bulan",
			Actual:             "95",
			Target:             "90",
			Calculation:        "105.56%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA96",
			GoalID:             "G-010",
			StrategicObjective: "Penerapan Quality Assurance and Improvement Program (QAIP Internal & External Review)",
			KPI:                "Tingkat kesesuaian praktik audit internal terhadap Standar Internasional IIA (IPPF)",
			Unit:               "predikat/score",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "80.0", "2025": "82.0", "2026": "85.0", "2027": "88.0", "2028": "90.0"},
			KPIActuals:         map[string]string{"2024": "81.5", "2025": "83.5", "2026": "86.0", "2027": "", "2028": ""},
			InternalAuditSO:    "Menjamin kualitas asurans internal audit",
			Actual:             "86.0",
			Target:             "85.0",
			Calculation:        "101.18%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA97",
			GoalID:             "G-010",
			StrategicObjective: "Pelaksanaan peran Strategic Partner dan pemberian layanan konsultansi (Advisory Services)",
			KPI:                "Jumlah layanan konsultansi dan advisory review yang dilaksanakan atas permintaan direksi",
			Unit:               "jumlah",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "2", "2025": "3", "2026": "4", "2027": "5", "2028": "6"},
			KPIActuals:         map[string]string{"2024": "3", "2025": "4", "2026": "5", "2027": "", "2028": ""},
			InternalAuditSO:    "Melaksanakan peran strategic partner",
			Actual:             "5",
			Target:             "4",
			Calculation:        "125.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA98",
			GoalID:             "G-010",
			StrategicObjective: "Peningkatan pemanfaatan teknik audit berbantuan komputer (Continuous Auditing / CAATs)",
			KPI:                "Persentase penugasan audit yang memanfaatkan automated data analytics & CAATs",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "40", "2025": "55", "2026": "70", "2027": "80", "2028": "90"},
			KPIActuals:         map[string]string{"2024": "45", "2025": "60", "2026": "75", "2027": "", "2028": ""},
			InternalAuditSO:    "Meningkatkan cakupan pengujian transaksi dari sampling manual menjadi 100% populasi",
			Actual:             "75",
			Target:             "70",
			Calculation:        "107.14%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA99",
			GoalID:             "G-010",
			StrategicObjective: "Kecepatan penerbitan Alert Memo dan rekomendasi darurat atas temuan kritis",
			KPI:                "Rata-rata waktu penerbitan Audit Alert Memo sejak temuan berisiko critical ditemukan (jam)",
			Unit:               "Hour",
			HibHig:             "HIB",
			PeriodType:         "Quartal",
			SelectedPeriod:     "Q1",
			YearStart:          2026,
			YearEnd:            2027,
			KPITargets:         map[string]string{"Q1": "24", "Q2": "24", "Q3": "12", "Q4": "12"},
			KPIActuals:         map[string]string{"Q1": "12", "Q2": "", "Q3": "", "Q4": ""},
			InternalAuditSO:    "Memberikan peringatan dini ke manajemen sebelum potensi kerugian membesar",
			Actual:             "12",
			Target:             "24",
			Calculation:        "200.00%",
			Status:             "Good",
		},
		{
			Code:               "SO-IA100",
			GoalID:             "G-010",
			StrategicObjective: "Efisiensi realisasi anggaran unit kerja audit internal terhadap anggaran tahunan (Cost to Value)",
			KPI:                "Persentase penyerapan anggaran operasional audit tanpa melampaui plafon RKAP",
			Unit:               "%",
			HibHig:             "HIG",
			PeriodType:         "Yearly",
			SelectedPeriod:     "2026",
			YearStart:          2024,
			YearEnd:            2028,
			KPITargets:         map[string]string{"2024": "95", "2025": "95", "2026": "98", "2027": "98", "2028": "98"},
			KPIActuals:         map[string]string{"2024": "96", "2025": "97", "2026": "98", "2027": "", "2028": ""},
			InternalAuditSO:    "Menjaga akuntabilitas dan efisiensi pengeluaran perjalanan dinas dan operasional audit",
			Actual:             "98",
			Target:             "98",
			Calculation:        "100.00%",
			Status:             "Good",
		},
	}
}
