#!/bin/sh
# ============================================================================
# AuditSphere Data Hub — Dynamic PostgreSQL & TimescaleDB Auto-Tuner
# Evaluates host/container memory & vCPUs to output optimal postgresql configs
# ============================================================================

set -e

CONF_DIR="/etc/postgresql/conf.d"
mkdir -p "$CONF_DIR"
TARGET_CONF="$CONF_DIR/00-autotune.conf"

PROFILE="${HARDWARE_PROFILE:-auto}"

# 1. Detect Total Available Memory in MB
detect_mem_mb() {
    # Check cgroup v2
    if [ -f "/sys/fs/cgroup/memory.max" ] && [ "$(cat /sys/fs/cgroup/memory.max)" != "max" ]; then
        bytes=$(cat /sys/fs/cgroup/memory.max)
        echo $((bytes / 1024 / 1024))
        return
    fi
    # Check cgroup v1
    if [ -f "/sys/fs/cgroup/memory/memory.limit_in_bytes" ]; then
        bytes=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
        # Avoid unlimited value (e.g. > 1000 TB)
        if [ "$bytes" -lt 1000000000000000 ]; then
            echo $((bytes / 1024 / 1024))
            return
        fi
    fi
    # Fallback to /proc/meminfo
    if [ -f "/proc/meminfo" ]; then
        kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')
        echo $((kb / 1024))
        return
    fi
    # Default fallback: 4096 MB
    echo 4096
}

# 2. Detect CPU Cores
detect_cpus() {
    if [ -f "/proc/cpuinfo" ]; then
        grep -c processor /proc/cpuinfo || echo 2
        return
    fi
    echo 2
}

MEM_MB=$(detect_mem_mb)
CPUS=$(detect_cpus)
[ "$CPUS" -lt 1 ] && CPUS=1

echo "[AutoTune] Detected Memory: ${MEM_MB}MB, CPUs: ${CPUS}, Profile: ${PROFILE}"

if [ "$PROFILE" = "demo" ] || ([ "$PROFILE" = "auto" ] && [ "$MEM_MB" -le 8192 ]); then
    echo "[AutoTune] Applying Demo VPS Profile (Optimized for KVM 2 / <= 8GB RAM)..."
    SHARED_BUFFERS="768MB"
    EFFECTIVE_CACHE="2560MB"
    MAINT_WORK_MEM="256MB"
    WORK_MEM="16MB"
    MAX_PARALLEL_WORKERS_PER_GATHER="1"
    MAX_WORKER_PROCESSES="8"
    MAX_PARALLEL_WORKERS="2"
    TIMESCALEDB_WORKERS="2"
    MAX_WAL_SIZE="2GB"
elif [ "$PROFILE" = "prod" ] || ([ "$PROFILE" = "auto" ] && [ "$MEM_MB" -gt 32768 ]); then
    echo "[AutoTune] Applying High-Throughput Production Profile (64GB+ RAM)..."
    SHARED_BUFFERS="10GB"
    EFFECTIVE_CACHE="30GB"
    MAINT_WORK_MEM="2GB"
    WORK_MEM="64MB"
    MAX_PARALLEL_WORKERS_PER_GATHER="4"
    MAX_WORKER_PROCESSES="32"
    MAX_PARALLEL_WORKERS="8"
    TIMESCALEDB_WORKERS="12"
    MAX_WAL_SIZE="16GB"
else
    # Auto calculation for mid-tier systems (e.g. 16GB-32GB)
    echo "[AutoTune] Applying Adaptive Calculated Profile..."
    SB_VAL=$((MEM_MB / 4))
    SHARED_BUFFERS="${SB_VAL}MB"

    EC_VAL=$((MEM_MB * 3 / 4))
    EFFECTIVE_CACHE="${EC_VAL}MB"

    MWM_VAL=$((MEM_MB / 20))
    [ "$MWM_VAL" -gt 2048 ] && MWM_VAL=2048
    [ "$MWM_VAL" -lt 128 ] && MWM_VAL=128
    MAINT_WORK_MEM="${MWM_VAL}MB"

    WM_VAL=$(( (MEM_MB - SB_VAL) / 300 ))
    [ "$WM_VAL" -lt 16 ] && WM_VAL=16
    [ "$WM_VAL" -gt 128 ] && WM_VAL=128
    WORK_MEM="${WM_VAL}MB"

    MAX_PARALLEL_WORKERS_PER_GATHER=$((CPUS / 4))
    [ "$MAX_PARALLEL_WORKERS_PER_GATHER" -lt 1 ] && MAX_PARALLEL_WORKERS_PER_GATHER=1

    MAX_PARALLEL_WORKERS=$((CPUS / 2))
    [ "$MAX_PARALLEL_WORKERS" -lt 2 ] && MAX_PARALLEL_WORKERS=2

    MAX_WORKER_PROCESSES=$((CPUS * 2))
    [ "$MAX_WORKER_PROCESSES" -lt 4 ] && MAX_WORKER_PROCESSES=4

    TIMESCALEDB_WORKERS=$((CPUS))
    [ "$TIMESCALEDB_WORKERS" -lt 2 ] && TIMESCALEDB_WORKERS=2
    [ "$TIMESCALEDB_WORKERS" -gt 8 ] && TIMESCALEDB_WORKERS=8

    MAX_WAL_SIZE="8GB"
fi

cat <<EOF > "$TARGET_CONF"
# --- Dynamically generated by AuditSphere autotune.sh on $(date) ---
shared_buffers = ${SHARED_BUFFERS}
effective_cache_size = ${EFFECTIVE_CACHE}
maintenance_work_mem = ${MAINT_WORK_MEM}
work_mem = ${WORK_MEM}
max_worker_processes = ${MAX_WORKER_PROCESSES}
max_parallel_workers = ${MAX_PARALLEL_WORKERS}
max_parallel_workers_per_gather = ${MAX_PARALLEL_WORKERS_PER_GATHER}
timescaledb.max_background_workers = ${TIMESCALEDB_WORKERS}
max_wal_size = ${MAX_WAL_SIZE}
EOF

echo "[AutoTune] Configuration written to $TARGET_CONF:"
cat "$TARGET_CONF"
